/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const LocalSvgIcon: (props: {
    name: "icon-empty-default" | "icon-empty-error" | "icon-empty-network" | "icon-empty-search" | "icon-forbidden" | "icon-logo" | "icon-moon" | "icon-not-found" | "icon-server-error" | "icon-sun-moon" | "icon-sunny"
    className?: string
    style?: React.CSSProperties
  }) => JSX.Element;
  export const svgNames: ["icon-empty-default", "icon-empty-error", "icon-empty-network", "icon-empty-search", "icon-forbidden", "icon-logo", "icon-moon", "icon-not-found", "icon-server-error", "icon-sun-moon", "icon-sunny"];
  export type SvgName = "icon-empty-default" | "icon-empty-error" | "icon-empty-network" | "icon-empty-search" | "icon-forbidden" | "icon-logo" | "icon-moon" | "icon-not-found" | "icon-server-error" | "icon-sun-moon" | "icon-sunny";
  export default LocalSvgIcon;
}
