/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as TabbarRouteRouteImport } from './pages/_tabbar/route'
import { Route as AuthenticatedRouteRouteImport } from './pages/_authenticated/route'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ExamplePaginationRouteImport } from './pages/example/pagination'
import { Route as ExampleMockRouteImport } from './pages/example/mock'
import { Route as ExampleIconRouteImport } from './pages/example/icon'
import { Route as ExampleEchartsRouteImport } from './pages/example/echarts'
import { Route as TabbarMineRouteImport } from './pages/_tabbar/mine'
import { Route as TabbarHomeRouteImport } from './pages/_tabbar/home'
import { Route as TabbarExampleRouteImport } from './pages/_tabbar/example'
import { Route as AuthenticatedSettingsRouteImport } from './pages/_authenticated/settings'
import { Route as errors500RouteImport } from './pages/(errors)/500'
import { Route as errors404RouteImport } from './pages/(errors)/404'
import { Route as errors403RouteImport } from './pages/(errors)/403'
import { Route as authSignUpRouteImport } from './pages/(auth)/sign-up'
import { Route as authSignInRouteImport } from './pages/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './pages/(auth)/forgot-password'

const TabbarRouteRoute = TabbarRouteRouteImport.update({
  id: '/_tabbar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplePaginationRoute = ExamplePaginationRouteImport.update({
  id: '/example/pagination',
  path: '/example/pagination',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleMockRoute = ExampleMockRouteImport.update({
  id: '/example/mock',
  path: '/example/mock',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleIconRoute = ExampleIconRouteImport.update({
  id: '/example/icon',
  path: '/example/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleEchartsRoute = ExampleEchartsRouteImport.update({
  id: '/example/echarts',
  path: '/example/echarts',
  getParentRoute: () => rootRouteImport,
} as any)
const TabbarMineRoute = TabbarMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => TabbarRouteRoute,
} as any)
const TabbarHomeRoute = TabbarHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TabbarRouteRoute,
} as any)
const TabbarExampleRoute = TabbarExampleRouteImport.update({
  id: '/example',
  path: '/example',
  getParentRoute: () => TabbarRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/settings': typeof AuthenticatedSettingsRoute
  '/example': typeof TabbarExampleRoute
  '/home': typeof TabbarHomeRoute
  '/mine': typeof TabbarMineRoute
  '/example/echarts': typeof ExampleEchartsRoute
  '/example/icon': typeof ExampleIconRoute
  '/example/mock': typeof ExampleMockRoute
  '/example/pagination': typeof ExamplePaginationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/settings': typeof AuthenticatedSettingsRoute
  '/example': typeof TabbarExampleRoute
  '/home': typeof TabbarHomeRoute
  '/mine': typeof TabbarMineRoute
  '/example/echarts': typeof ExampleEchartsRoute
  '/example/icon': typeof ExampleIconRoute
  '/example/mock': typeof ExampleMockRoute
  '/example/pagination': typeof ExamplePaginationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_tabbar': typeof TabbarRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_tabbar/example': typeof TabbarExampleRoute
  '/_tabbar/home': typeof TabbarHomeRoute
  '/_tabbar/mine': typeof TabbarMineRoute
  '/example/echarts': typeof ExampleEchartsRoute
  '/example/icon': typeof ExampleIconRoute
  '/example/mock': typeof ExampleMockRoute
  '/example/pagination': typeof ExamplePaginationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/403'
    | '/404'
    | '/500'
    | '/settings'
    | '/example'
    | '/home'
    | '/mine'
    | '/example/echarts'
    | '/example/icon'
    | '/example/mock'
    | '/example/pagination'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/403'
    | '/404'
    | '/500'
    | '/settings'
    | '/example'
    | '/home'
    | '/mine'
    | '/example/echarts'
    | '/example/icon'
    | '/example/mock'
    | '/example/pagination'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_tabbar'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/_authenticated/settings'
    | '/_tabbar/example'
    | '/_tabbar/home'
    | '/_tabbar/mine'
    | '/example/echarts'
    | '/example/icon'
    | '/example/mock'
    | '/example/pagination'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  TabbarRouteRoute: typeof TabbarRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  ExampleEchartsRoute: typeof ExampleEchartsRoute
  ExampleIconRoute: typeof ExampleIconRoute
  ExampleMockRoute: typeof ExampleMockRoute
  ExamplePaginationRoute: typeof ExamplePaginationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tabbar': {
      id: '/_tabbar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabbarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/pagination': {
      id: '/example/pagination'
      path: '/example/pagination'
      fullPath: '/example/pagination'
      preLoaderRoute: typeof ExamplePaginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/mock': {
      id: '/example/mock'
      path: '/example/mock'
      fullPath: '/example/mock'
      preLoaderRoute: typeof ExampleMockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/icon': {
      id: '/example/icon'
      path: '/example/icon'
      fullPath: '/example/icon'
      preLoaderRoute: typeof ExampleIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/echarts': {
      id: '/example/echarts'
      path: '/example/echarts'
      fullPath: '/example/echarts'
      preLoaderRoute: typeof ExampleEchartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabbar/mine': {
      id: '/_tabbar/mine'
      path: '/mine'
      fullPath: '/mine'
      preLoaderRoute: typeof TabbarMineRouteImport
      parentRoute: typeof TabbarRouteRoute
    }
    '/_tabbar/home': {
      id: '/_tabbar/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof TabbarHomeRouteImport
      parentRoute: typeof TabbarRouteRoute
    }
    '/_tabbar/example': {
      id: '/_tabbar/example'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof TabbarExampleRouteImport
      parentRoute: typeof TabbarRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TabbarRouteRouteChildren {
  TabbarExampleRoute: typeof TabbarExampleRoute
  TabbarHomeRoute: typeof TabbarHomeRoute
  TabbarMineRoute: typeof TabbarMineRoute
}

const TabbarRouteRouteChildren: TabbarRouteRouteChildren = {
  TabbarExampleRoute: TabbarExampleRoute,
  TabbarHomeRoute: TabbarHomeRoute,
  TabbarMineRoute: TabbarMineRoute,
}

const TabbarRouteRouteWithChildren = TabbarRouteRoute._addFileChildren(
  TabbarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  TabbarRouteRoute: TabbarRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  ExampleEchartsRoute: ExampleEchartsRoute,
  ExampleIconRoute: ExampleIconRoute,
  ExampleMockRoute: ExampleMockRoute,
  ExamplePaginationRoute: ExamplePaginationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
